#!/bin/sh
#
# Start/stop hiawatha
#

PIDFILE=/var/run/hiawatha.pid

case "$1" in
  start)
	printf "Starting hiawatha..."
	mkdir -p /var/log/hiawatha /var/lib/hiawatha
	start-stop-daemon -S -x /usr/sbin/hiawatha -p $PIDFILE
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping hiawatha..."
	start-stop-daemon -K -q -p $PIDFILE
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
