#ifndef __HI_IRQS_H__
#define __HI_IRQS_H__

#define HISI_VIC_IRQ_START		(0)

#define INTNR_WATCHDOG			(HISI_VIC_IRQ_START + 1)

#define INTNR_TIMER_0			(HISI_VIC_IRQ_START + 3)
#define INTNR_TIMER_1			(HISI_VIC_IRQ_START + 3)
#define INTNR_TIMER_2			(HISI_VIC_IRQ_START + 4)
#define INTNR_TIMER_3			(HISI_VIC_IRQ_START + 4)

#define INTNR_UART0			(HISI_VIC_IRQ_START + 5)
#define INTNR_UART1			(HISI_VIC_IRQ_START + 30)
#define INTNR_UART2			(HISI_VIC_IRQ_START + 25)

#define INTNR_GPIO			(HISI_VIC_IRQ_START + 31)
#define INTNR_GPIO0			(INTNR_GPIO)
#define INTNR_GPIO1			(INTNR_GPIO)
#define INTNR_GPIO2			(INTNR_GPIO)
#define INTNR_GPIO3			(INTNR_GPIO)
#define INTNR_GPIO4			(INTNR_GPIO)
#define INTNR_GPIO5			(INTNR_GPIO)
#define INTNR_GPIO6			(INTNR_GPIO)
#define INTNR_GPIO7			(INTNR_GPIO)
#define INTNR_GPIO8			(INTNR_GPIO)

#define INTNR_GPIO0_START		(HISI_VIC_IRQ_START + 32)
#define INTNR_GPIO0_END			(INTNR_GPIO0_START + 7)
#define INTNR_GPIO1_START		(INTNR_GPIO0_END + 1)
#define INTNR_GPIO1_END			(INTNR_GPIO1_START + 7)
#define INTNR_GPIO2_START		(INTNR_GPIO1_END + 1)
#define INTNR_GPIO2_END			(INTNR_GPIO2_START + 7)
#define INTNR_GPIO3_START		(INTNR_GPIO2_END + 1)
#define INTNR_GPIO3_END			(INTNR_GPIO3_START + 7)
#define INTNR_GPIO4_START		(INTNR_GPIO3_END + 1)
#define INTNR_GPIO4_END			(INTNR_GPIO4_START + 7)
#define INTNR_GPIO5_START		(INTNR_GPIO4_END + 1)
#define INTNR_GPIO5_END			(INTNR_GPIO5_START + 7)
#define INTNR_GPIO6_START		(INTNR_GPIO5_END + 1)
#define INTNR_GPIO6_END			(INTNR_GPIO6_START + 7)
#define INTNR_GPIO7_START		(INTNR_GPIO6_END + 1)
#define INTNR_GPIO7_END			(INTNR_GPIO7_START + 7)
#define INTNR_GPIO8_START		(INTNR_GPIO7_END + 1)
#define INTNR_GPIO8_END			(INTNR_GPIO8_START + 7)

#define NR_IRQS				(INTNR_GPIO8_END + 1)

#endif
