#
# The Flash Memory Controller v100 Device Driver for hisilicon
#
# Copyright (c) 2016 HiSilicon Technologies Co., Ltd.
#
# This program is free software; you can redistribute  it and/or modify it
# under  the terms of  the GNU General  Public License as published by the
# Free Software Foundation;  either version 2 of the  License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#

#
# drivers/mtd/nand/hifmc100/Makefile
#

obj-$(CONFIG_HIFMC_SPI_NAND)	+= hifmc_spi_nand_ids.o
obj-$(CONFIG_HIFMC100_SPI_NAND) += hifmc100.o hifmc100_os.o
