#/******************************************************************************
# *    Copyright (c) 2009-2012 by Hisi.
# *    All rights reserved.
# *
#******************************************************************************/

CROSS_COMPILE ?= arm-hisiv400-linux-

CPU    := hi3516a
COBJS  := ddr_training.o

include ../ddr_training.mk

