#ifndef __HI_IRQS_H__
#define __HI_IRQS_H__

#define GODNET_IRQ_START	(32)
#define COMMTX_IRQ		(GODNET_IRQ_START + 0)
#define TIMER01_IRQ		(GODNET_IRQ_START + 3)
#define TIMER23_IRQ		(GODNET_IRQ_START + 4)

#define UART0_IRQ		(GODNET_IRQ_START + 8)
#define UART1_IRQ		(GODNET_IRQ_START + 9)

#define INTNR_L2CACHE_CHK0_INT	(GODNET_IRQ_START+37)
#define INTNR_L2CACHE_CHK1_INT	(GODNET_IRQ_START+38)
#define INTNR_L2CACHE_INT_COMB	(GODNET_IRQ_START+39)
#define MAX_GIC_NR		1

#define NR_IRQS			(GODNET_IRQ_START + 96)
#define IRQ_LOCALTIMER		29
#endif

