#!/bin/sh
#
# Start live-streamer
#

SENSOR_TYPE=$(fw_printenv sensor_type 2>/dev/null)
SENSOR_TYPE=${SENSOR_TYPE:12}
SENSOR_TYPE=${SENSOR_TYPE:-ov9712}

start() {
    echo -n "Starting live-streamer: "
    start-stop-daemon -S -q -m -b -p /var/run/live-streamer.pid \
                      -x live-streamer -- -S ${SENSOR_TYPE}
    echo "OK"
}

stop() {
    echo -n "Stopping live-streamer: "
    start-stop-daemon -K -q -p /var/run/live-streamer.pid
    usleep 1000000
    echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
