#!/bin/sh
#
# Start himpp....
#

HIMPP_HOME=/opt/himpp2
SENSOR_TYPE=$(fw_printenv sensor_type 2>/dev/null)
SENSOR_TYPE=${SENSOR_TYPE:12}
SENSOR_TYPE=${SENSOR_TYPE:-gc1004}

start() {
    (
      echo -n "Starting himpp: "
      cd ${HIMPP_HOME}/ko
      ./load3518.sh -i ${SENSOR_TYPE}
      [ $? = 0 ] && echo "OK" || echo "FAIL"
    )
}

stop() {
    (
      echo -n "Stopping himpp: "
      cd ${HIMPP_HOME}/ko
      ./load3518.sh -r
      [ $? = 0 ] && echo "OK" || echo "FAIL"
    )
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
