
obj-$(CONFIG_MTD_NAND_HINFC504) += hinfc504.o hinfc504_os.o hinfc504_dbg.o \
	hinfc504_read_retry_hynix_bg_cdie.o \
	hinfc504_read_retry_hynix_bg_bdie.o \
	hinfc504_read_retry_hynix_cg_adie.o \
	hinfc504_read_retry_micron.o  \
	hinfc504_read_retry_samsung.o \
	hinfc504_read_retry_toshiba.o

obj-$(CONFIG_ARCH_HI3535) += hinfc504_hi3535.o
