#/******************************************************************************
# *    Copyright (c) 2009-2012 by Hisi.
# *    All rights reserved.
# *
#******************************************************************************/

CROSS_COMPILE ?= arm-hisiv200-linux-

CPU    := hi3535
COBJS  := ddr_training.o

include ../ddr_training.mk

