#
# Hisilicon Clock specific Makefile
#

obj-y	+= clk.o clkgate-separated.o clk_ops.o

obj-$(CONFIG_ARCH_HI3xxx)	+= clk-hi3620.o
obj-$(CONFIG_ARCH_HIP04)	+= clk-hip04.o
obj-$(CONFIG_ARCH_HIX5HD2)	+= clk-hix5hd2.o
obj-$(CONFIG_ARCH_HI3516CV300)	+= clk-hi3516cv300.o reset.o
obj-$(CONFIG_ARCH_HI3519)	+= clk-hi3519.o reset.o
obj-$(CONFIG_ARCH_HI3519V101)	+= clk-hi3519v101.o reset.o
obj-$(CONFIG_ARCH_HI3516AV200)	+= clk-hi3516av200.o reset.o
obj-$(CONFIG_ARCH_HI3559)	+= clk-hi3559.o reset.o
obj-$(CONFIG_ARCH_HI3556)	+= clk-hi3556.o reset.o
obj-$(CONFIG_ARCH_HI3536C)	+= clk-hi3536c.o reset.o
