#
# drivers/nand/hinfc301/Makefile
#
obj-$(CONFIG_MTD_NAND_HINFC301)     += hinfc301.o

ifdef CONFIG_ARCH_GODBOX
obj-$(CONFIG_MTD_NAND_HINFC301)     += hinfc301_godbox.o
endif

ifdef CONFIG_ARCH_GODEYES
obj-$(CONFIG_MTD_NAND_HINFC301)     += hinfc301_godeyes.o
endif

ifdef CONFIG_ARCH_GODNET
obj-$(CONFIG_MTD_NAND_HINFC301)     += hinfc301_godnet.o
endif

ifdef CONFIG_ARCH_GODARM
obj-$(CONFIG_MTD_NAND_HINFC301)     += hinfc301_godarm.o
endif

ifdef CONFIG_ARCH_PHOENIX
obj-$(CONFIG_MTD_NAND_HINFC301)     += hinfc301_phoenix.o
endif

ifdef CONFIG_ARCH_HI3518
obj-$(CONFIG_MTD_NAND_HINFC301)	    += hinfc301_3518.o
endif
