#
# Makefile for the HISILICON network device drivers.
#

obj-$(CONFIG_HIX5HD2_GMAC) += hix5hd2_gmac.o
obj-$(CONFIG_HISI_FEMAC) += hisi_femac.o
obj-$(CONFIG_HIETH_GMAC) += higmac/
obj-$(CONFIG_HIETH_SWITCH_FABRIC) += hieth/
