#!/bin/sh
#
# Start live-streamer
#

SENSOR_TYPE=$(. /lib/scripts/hardware.sh; detect_sensor_type)

CONFIGFILE=/etc/config/live-streamer-${SENSOR_TYPE}.conf
[ -f "$CONFIGFILE" ] || cp -f /etc/config/live-streamer.conf "$CONFIGFILE"

VSRC0OPT="-vsrc isp0:sensor=${SENSOR_TYPE}|videv0|vichn0|vpgrp0|vpchn0"
#VENC0OPT="-venc vpchn0|vechn0:encoding=H264,framerate=15,resolution=D1"
VENC1OPT="-venc vpchn0|vechn1:encoding=H264,framerate=25,resolution=720P"
VENC2OPT="-venc vpchn0|vechn2:encoding=MJPEG,framerate=5"
#ASRC0OPT="-asrc acodec0|aidev0|aichn0"
#AENC0OPT="-aenc aichn0|aechn0:encoding=G711A"
#STREAMOPT="-stream 0:vechn0 -stream record:vechn1 -stream snapshot:vechn2"
STREAMOPT="-stream 0:vechn1 -stream snapshot:venchn2"
#MEDIA_OPTIONS="$VSRC0OPT $VENC0OPT $VENC1OPT $VENC2OPT $STREAMOPT"
MEDIA_OPTIONS="$VSRC0OPT $VENC1OPT $VENC2OPT $STREAMOPT"

start() {
    echo -n "Starting live-streamer: "
    start-stop-daemon -S -q -m -b -p /var/run/live-streamer.pid \
                      -x live-streamer -- -S -c${CONFIGFILE} ${MEDIA_OPTIONS}
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    echo -n "Stopping live-streamer: "
    start-stop-daemon -K -q -p /var/run/live-streamer.pid
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    usleep 1000000
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
